services:
  - type: worker
    name: bot-servicios-whatsapp
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: OWNER_PHONE
        sync: false
      - key: PAIRING_PHONE
        sync: false
      - key: MULTIPLIER_250
        value: "20"
      - key: MULTIPLIER_35
        value: "20"
      - key: LOG_LEVEL
        value: "info"
